/**
 * German search keywords for the most commonly searched-for category icons.
 * The picker also always matches against the icon's own (English) name, so
 * this only needs to cover terms that wouldn't otherwise match.
 */
export const ICON_KEYWORDS: Record<string, string> = {
  Home: 'haus wohnen miete',
  Building: 'gebäude haus wohnung',
  Building2: 'gebäude firma büro',
  Zap: 'strom energie elektrizität',
  Flame: 'gas heizung feuer',
  Droplet: 'wasser tropfen',
  Wifi: 'internet netz wlan',
  ShieldCheck: 'versicherung schutz sicherheit',
  Car: 'auto fahrzeug pkw',
  Bike: 'fahrrad rad',
  Bus: 'bus öpnv nahverkehr',
  Train: 'bahn zug',
  Plane: 'flugzeug flug reise urlaub',
  Fuel: 'tanken benzin sprit tankstelle',
  ParkingCircle: 'parken parkplatz',
  ParkingSquare: 'parken parkplatz',
  Smartphone: 'handy telefon mobil',
  Phone: 'telefon anruf',
  Laptop: 'computer pc technik',
  Tv: 'fernseher fernsehen streaming',
  Gamepad2: 'spiele gaming videospiele konsole',
  Clapperboard: 'film kino streaming',
  Music: 'musik lied',
  Headphones: 'kopfhörer musik audio',
  AppWindow: 'software app programm',
  CreditCard: 'kredit karte zahlung bank',
  Wallet: 'geld geldbeutel finanzen',
  PiggyBank: 'sparen sparschwein geld',
  Landmark: 'bank finanzamt behörde',
  TrendingUp: 'wachstum gewinn aktien',
  TrendingDown: 'verlust rückgang',
  Receipt: 'rechnung beleg quittung',
  Banknote: 'geld schein bargeld',
  Coins: 'geld münzen kleingeld',
  Calculator: 'rechner steuer',
  Users: 'familie gruppe menschen mitgliedschaft',
  Heart: 'liebe familie herz',
  HeartPulse: 'gesundheit arzt herz',
  Stethoscope: 'arzt gesundheit medizin',
  Pill: 'medikament apotheke tablette',
  Syringe: 'impfung spritze arzt',
  Bandage: 'verletzung pflaster erste hilfe',
  Ambulance: 'notfall krankenwagen rettung',
  Dumbbell: 'sport fitness gym training',
  Baby: 'kind kleinkind familie',
  PawPrint: 'tier haustier',
  Dog: 'hund haustier tier',
  Cat: 'katze haustier tier',
  Fish: 'fisch aquarium haustier',
  GraduationCap: 'bildung schule studium uni',
  BookOpen: 'buch lesen bildung',
  Book: 'buch lesen',
  School: 'schule bildung kita',
  Briefcase: 'arbeit büro job beruf',
  ShoppingCart: 'einkaufen einkauf supermarkt',
  ShoppingBag: 'einkaufen shopping kleidung',
  Utensils: 'essen restaurant lebensmittel',
  UtensilsCrossed: 'essen restaurant',
  ChefHat: 'kochen essen restaurant',
  Coffee: 'kaffee café',
  Pizza: 'essen pizza lieferservice',
  Beer: 'bier alkohol',
  Wine: 'wein alkohol',
  Shirt: 'kleidung mode',
  Scissors: 'friseur schnitt',
  Watch: 'uhr accessoire',
  Glasses: 'brille optiker',
  Gift: 'geschenk geburtstag',
  Ticket: 'ticket veranstaltung kino konzert',
  Trophy: 'sport gewinn pokal',
  Camera: 'foto kamera',
  Umbrella: 'regen wetter versicherung',
  Leaf: 'garten natur pflanze',
  Trees: 'garten natur baum',
  Flower2: 'garten blume pflanze',
  Recycle: 'müll recycling abfall',
  Globe: 'internet welt reise',
  MapPin: 'ort standort reise',
  Map: 'reise karte navigation',
  Compass: 'reise navigation',
  Backpack: 'reise rucksack schule',
  Luggage: 'reise koffer urlaub',
  Wrench: 'reparatur werkzeug handwerker',
  Hammer: 'werkzeug handwerker reparatur',
  Drill: 'werkzeug handwerker bohren',
  Truck: 'umzug transport lieferung',
  Newspaper: 'zeitung abo nachrichten',
  Mail: 'post email brief',
  KeyRound: 'schlüssel wohnung',
  Key: 'schlüssel',
  Lock: 'sicherheit schloss',
  Bath: 'bad badezimmer',
  Sofa: 'möbel wohnzimmer',
  Bed: 'möbel schlafzimmer bett',
  Lamp: 'möbel licht lampe',
  Fan: 'klimaanlage lüfter',
  Thermometer: 'heizung temperatur fieber',
  Refrigerator: 'kühlschrank küche',
  Microwave: 'küche mikrowelle',
  WashingMachine: 'waschmaschine haushalt',
  Factory: 'arbeit industrie',
  Store: 'laden geschäft',
  Hotel: 'übernachtung reise urlaub',
  Vault: 'bank tresor',
  Scale: 'anwalt recht gewicht',
  Gavel: 'anwalt recht gericht',
  MoreHorizontal: 'sonstiges andere',
}
